Borre y cargué la carpeta nuevamente
Por terminal me sale error
 ! [rejected]        master -> master (fetch first)
error: falló el empuje de algunas referencias a 'https://github.com/ezemoliph/ezemoliph.github.io.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.